#! /bin/sh

FIRST_DESK=1
REMAINING_DESKS="$(seq 2 9) 0"
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS

export BSPWM_SOCKET=/tmp/bspwm-socket

bspc config split_ratio 0.52
bspc config bottom_padding 23
bspc config border_width 2
bspc config window_gap 8
bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config apply_shadow_property true
bspc config adaptative_raise true
bspc config fence_grip 100
bspc config focused_border_color "#aa6300"  #"#11809E"
bspc config active_border_color "#1D667A"
bspc config normal_border_color "#222222" #"#3F3E3B"
bspc config presel_border_color "#A7BF81"
bspc config focused_locked_border_color "#C7B579"
bspc config active_locked_border_color "#7E7F89"
bspc config normal_locked_border_color "#3F3E3B"
bspc config urgent_border_color "#EFA29A"

bspc rule Geary floating
bspc rule Nautilus floating
bspc rule Gimp floating
bspc rule -a Firefox -d 2
bspc rule -a Vlc -d 3
bspc rule -a rtorrent -d 3
bspc rule -a URthree -d 3


bspc monitor -p 14 0 0 0

bspc add Desktop02 Desktop03 Desktop04

~/.config/bspwm/panel &

## Predefined Workspace 1
urxvtc && urxvtc && urxvtc

## Predefined Workspace 2
firefox &

## Predefined Workspace 3

urxvtc -name rtorrent -e rtorrent &
urxvtc -name URthree & vlc &
