#!/bin/bash

FIRST_DESK=1
REMAINING_DESKS="$(seq 2 9) 0"
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS

export BSPWM_SOCKET=/tmp/bspwm-socket

bspc config split_ratio     0.52
bspc config bottom_padding  23
bspc config border_width    2
bspc config window_gap      8
bspc config fence_grip      100
bspc config focus_follows_pointer   true
bspc config click_to_focus          true
bspc config gapless_monocle         true
bspc config borderless_monocle      true
bspc config apply_shadow_property   true
bspc config adaptative_raise        true

bspc config focused_border_color        "#ac7311"  #"#11809E"
bspc config focused_locked_border_color "#C7B579"

bspc config active_border_color         "#004455"
bspc config active_locked_border_color  "#7E7F89"

bspc config normal_border_color         "#222222" #"#3F3E3B"
bspc config normal_locked_border_color  "#3F3E3B"

bspc config presel_border_color         "#A7BF81"
bspc config urgent_border_color         "#EFA29A"

bspc rule -a Geary --floating
bspc rule -a Nautilus --floating
bspc rule -a Gimp --floating
bspc rule -a Firefox -d 2
bspc rule -a Vlc -d 3
bspc rule -a rtorrent -d 3
bspc rule -a URthree -d 3

bspc monitor -p 14 0 0 0

~/.config/bspwm/panel &

## Predefined Workspace 1
urxvtc && urxvtc && urxvtc

## Predefined Workspace 2
firefox &

## Predefined Workspace 3
#urxvtc -name URthree && vlc &
#sleep 5 && urxvtc -name rtorrent -e rtorrent

urxvtc -name rtorrent -e rtorrent
bspc window $(bspc query -W -d 3) -p right

urxvtc -name URthree
bspc window $(bspc query -W -d 3|tail -1) -p up

vlc &

bspc window $(bspc query -W -d 3|tail -1) -e left 0.4 && bspc window $(bspc query -W -d 3|tail -1) -e up 0.7


#BW=$(bspc config border_width)
#bspc config window_gap -$BW
#for m in $(bspc query -M) ; do
#   bspc pad "$m" $BW $BW $BW $BW
#done
