#! /bin/sh

fwid=$(bspc query -W -w)

if [ -n "$fwid" ] ; then
    set -- $(wattr wh $fwid)
    if [ $1 -gt $2 ] ; then
        echo "split_dir=left"
    else
        echo "split_dir=down"
    fi
    echo "split_ratio=0.5"
fi
