#!/bin/zsh


## Predefined Workspace 1
desktop1() {
    	#urxvtc && urxvtc && urxvtc
	urxvtc && urxvtc && urxvtc
}

## Predefined Workspace 2
desktop2() {
	bspc desktop '^2' -l monocle
	firefox
#	firejail --dns=8.8.8.8 --dns=8.8.4.4 --net=enp0s25 firefox
}

## Predefined Workspace 3
desktop3() {
    urxvtc -name URthree && urxvtc -name rtorrent -e firejail --net=enp0s25 rtorrent &
}

## Predefined Workspace 4
desktop4() {
	#urxvtc -name mutt -e mutt &
	urxvtc -name mutt -e firejail --net=enp0s25 mutt &
}

desktop5() {
	urxvtc -name weechat -e firejail --net=enp0s25 weechat-curses
}

desktop6() {
	urxvtc -name rtv -fn "xft:PragmataPro:style=Regular:pixelsize=12, \
	xft:Inconsolata for Powerline:pixelsize=11,xft:SauceCodePro NF,xft:FontAwesome" \
	-e rtv -s linux
	urxvtc -name rtv -fn "xft:PragmataPro:style=Regular:pixelsize=12, \
	xft:Inconsolata for Powerline:pixelsize=11,xft:SauceCodePro NF,xft:FontAwesome" \
	-e rtv -s unixporn
	urxvtc -name rtv -fn "xft:PragmataPro:style=Regular:pixelsize=12, \
	xft:Inconsolata for Powerline:pixelsize=11,xft:SauceCodePro NF,xft:FontAwesome" \
	-e rtv -s archlinux
}

desktop1 &
desktop2 &
desktop3 &
desktop4 &
desktop5 &
desktop6
