#!/bin/zsh


## Predefined Workspace 1
desktop1() {
    urxvtc && urxvtc && urxvtc
}

## Predefined Workspace 2
desktop2() {
	bspc desktop web -l monocle
	firefox
}

## Predefined Workspace 3
desktop3() {
    urxvtc -name URthree && urxvtc -name rtorrent -e rtorrent &
}

## Predefined Workspace 4
desktop4() {
	urxvtc -name mutt -e mutt &
}

desktop5() {
	urxvtc -name weechat -e weechat-curses
}

desktop1 &
desktop2 &
desktop3 &
#desktop4 &
desktop5 #
