#!/bin/bash

#export BSPWM_SOCKET=/tmp/bspwm-socket

bspc monitor -d {term,web,media,mail,chat,other,temp}
bspc desktop -f 1

bspc config split_ratio     0.52
bspc config top_padding     14
bspc config bottom_padding  80
bspc config right_padding   62
bspc config border_width    2
bspc config window_gap      8
bspc config fence_grip      100
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false
bspc config click_to_focus		false
bspc config gapless_monocle		true
bspc config borderless_monocle		true
bspc config apply_shadow_property	true
bspc config adaptative_raise		true
#bspc config initial_polarity 		second_child

bspc config focused_border_color        "#ac7311"  #"#11809E"
bspc config focused_locked_border_color "#C7B579"

bspc config active_border_color         "#004455"
bspc config active_locked_border_color  "#7E7F89"

bspc config normal_border_color         "#222222" #"#3F3E3B"
bspc config normal_locked_border_color  "#3F3E3B"

bspc config presel_border_color         "#A7BF81"
bspc config urgent_border_color         "#EFA29A"


#if [ -e "$BSPWM_TREE" ] ; then
#   bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
#   rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
#fi

#bspc config external_rules_command "$(command -v external_rules)"

bspc rule -a Popcorntime	desktop=^3 tiled=on focused=off state=floating
bspc rule -a Geary		desktop=^4 floating=on center=on
bspc rule -a Firefox 		desktop=^2 tiled=on focused=off
bspc rule -a Quirky		desktop=^5 state=floating
bspc rule -a mpv		desktop=^3 state=floating
bspc rule -a gl 		desktop=^3 state=floating
bspc rule -a SessionManager	desktop=^2 state=floating
bspc rule -a Gimp		desktop=^6 tiled=on
bspc rule -a URthree		desktop=^3
bspc rule -a mutt		desktop=^4
bspc rule -a weechat		desktop=^5
bspc rule -a rtorrent 		desktop=^3
bspc rule -a Nautilus 		state=floating
bspc rule -a Pavucontrol	state=floating
bspc rule -a Acroread		state=floating
bspc rule -a Pinentry		state=floating
bspc rule -a bashrun2 		state=floating
bspc rule -a tempterm 		state=floating

## Focus last monitor
#bspc monitor -f ^$NMON

panel &

bsp_launch &


