#!/bin/bash

#FIRST_DESK=1
#REMAINING_DESKS="$(seq 1 9) 0"
#bspc monitor -a $REMAINING_DESKS

#bspc desktop -n 1 # $FIRST_DESK

#i=1
#for monitor in $(bspc query -M); do
#    bspc monitor "^"$monitor -n "$i" -d {I,II,III,IV,V,VI} #$i/{One,Two,Three,Four,Five,Six}
#    let i++
#done
#NMON=$i
#unset i

#export BSPWM_SOCKET=/tmp/bspwm-socket

bspc config split_ratio     0.52
bspc config top_padding     13
bspc config border_width    2
bspc config window_gap      8
bspc config fence_grip      100
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config click_to_focus          false
bspc config gapless_monocle         true
bspc config borderless_monocle      true
bspc config apply_shadow_property   true
bspc config adaptative_raise        true

bspc config focused_border_color        "#ac7311"  #"#11809E"
bspc config focused_locked_border_color "#C7B579"

bspc config active_border_color         "#004455"
bspc config active_locked_border_color  "#7E7F89"

bspc config normal_border_color         "#222222" #"#3F3E3B"
bspc config normal_locked_border_color  "#3F3E3B"

bspc config presel_border_color         "#A7BF81"
bspc config urgent_border_color         "#EFA29A"


#if [ -e "$BSPWM_TREE" ] ; then
#   bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
#   rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
#fi

bspc config external_rules_command "$(command -v external_rules)"

bspc monitor -d {term,web,media,mail,chat,other,temp}
bspc desktop -f 1

bspwm_rules #


## Focus last monitor
#bspc monitor -f ^$NMON

panel &

bsp_launch &
