#! /bin/bash


if ! rulc -l > /dev/null ; then
    (setsid ruld &)
    while ! rulc -l > /dev/null ; do
		sleep 0.1
    done
fi

rules=$(rulc -l)

    rulc -a 'class == "Geary"' 'floating=on,center=on'
    rulc -a 'class == "Nautilus"' 'floating=on'
    rulc -a 'calss == "Gimp"' 'floating=on'
    rulc -a 'class == "Firefox"' 'desktop=^2,focus=off'
    rulc -a 'class == "Vlc"' 'desktop=^3,floating=on'
    rulc -a 'instance == "rtorrent"' 'desktop=^3'
    rulc -a 'instance == "URthree"' 'desktop=^3'
    rulc -a 'instance == "mutt"' 'desktop=^4'
    rulc -a 'instance == "weechat"' 'desktop=^5'
    rulc -a 'class == "Budgie"' 'desktop=^6,floating=on'
fi
