#! /bin/bash


if ! rulc -l > /dev/null ; then
    (setsid ruld &)
    while ! rulc -l > /dev/null ; do
		sleep 0.1
    done
fi

rules=$(rulc -l)
if [ -z "$rules" ] ; then
	rulc -a 'class == "Nautilus"'	'floating=on'
	rulc -a 'class == "Firefox"'	'desktop=^2,tiled=on,focused=off'
	rulc -a 'class == "Dwb"'	'desktop=^2,tiled=on,focused=off'
	rulc -a 'class == "Vlc"'	'desktop=^3,floating=on'
	rulc -a 'class == "Popcorntime"' 'desktop=^3,floating=on'
	rulc -a 'class == "mpv"'	'desktop=^3' 'floating=on'
	rulc -a 'class == "Geary"'	'desktop=^4,floating=off,center=on'
	rulc -a 'class == "Quirky"'	'desktop=^5,floating=off'
	rulc -a 'calss == "Gimp"'	'desktop=^6,tiled=on'
	rulc -a 'class == "Budgie"'	'desktop=^6,floating=on'
	rulc -a 'class == "Pavucontrol"' 'floating=on'
	rulc -a 'class == "Personal.bin"' 'floating=on'
	rulc -a 'class == "Acroread"'	'floating=on'
	rulc -a 'class == "Pinentry"'	'floating=on'

	rulc -a 'instance == "URthree"' 'desktop=^3'
	rulc -a 'instance == "mutt"' 'desktop=^4'
	rulc -a 'instance == "weechat"' 'desktop=^5'
	rulc -a 'instance == "rtorrent"' 'desktop=^3'
	rulc -a 'instance == "gl"' 'desktop=^3,floating=on'
	rulc -a 'instance == "bashrun2"' 'floating=on'
	rulc -a 'instance == "tempterm"' 'floating=on'
fi
