#!/bin/bash

for p in {firefox,rtorrent,offlineimap,mutt,weechat-curses,rtv,panel};
do
        while :;
        do
                eval wmctrl -c firefox; \
                pkill -2 rtorrent; \
                pkill -USR2 offlineimap; \
                pkill -USR2 mutt; \
                pkill -USR2 weechat-curses; \
                pkill -2 rtv; \
		killall -9 panel{,_dzen2}

                pgrep -l $p
                [[ $? = 1 ]] && { break; };
        done
done

bspc quit

