#!/bin/bash

for p in {firefox-beta,rtorrent,offlineimap,mutt,weechat-curses,rtv,panel,panel_dzen2};
do
        while :;
        do
                eval wmctrl -c firefox-beta; \
                pkill -2 rtorrent; \
                pkill -USR2 offlineimap; \
                pkill -USR2 mutt; \
                pkill weechat-curses; \
                pkill -2 rtv; \
		killall -9 panel{,_dzen2}

                pgrep -l $p
                [[ $? = 1 ]] && { break; };
        done
done

bspc quit

