#!/bin/bash

shopt -s nullglob
cd ~/Downloads/Themes/Wallpapers/

while true; do
	files=()
	for i in *.jpg *.png *.jpe; do
		[[ -f $i ]] && files+=("$i")
	done
	range=${#files[@]}

	((range)) && feh --bg-center "${files[RANDOM % range]}"

	sleep 30m
done
