#!/bin/bash

dotfile_home="$HOME/.dotfiles/"
cd $dotfile_home

old_ifs=$IFS
IFS='
'


git_init() {
read -p ""
} 

git_push() {
    git status
    echo
    read -p "Enter your commit message: " git_commit 

    git add -A
    git commit -m "$git_commit"     # message input has to be quoted
    git push
}

while true; 
do
	case $1 in
		push) git_push ;;
		*) echo "No valid option entered... closing."; exit 1 ;;
	esac
done

IFS=$old_ifs
