#!/bin/bash

old_ifs=$IFS
IFS=$'\012' 

chk_init() {
	[[ ! -e "$HOME/.config/mkdotfile" ]] && {
		printf "\nMissing file. You probably need to\ndo a init first\n\n"
		exit 1 
	}
}

git_init() {

	printf "This will create a directory where you will\nstore your dotfiles\n\n"

	read -p "Enter dotfile directory: " dotfile_home

	[[ ! -d $dotfile_home ]] && { 
		echo "creating dir"
		mkdir -p $dotfile_home 
		echo "$dotfile_home" > $HOME/.config/mkdotfile
		break
	} || { 
		echo "\n\nDirectory already exist"
	}

        cd $(< "$HOME/.config/mkdotfile")
	read -p "Enter git repository url: " dotfile_home

} 

git_push() {
	chk_init
	cd $(< "$HOME/.config/mkdotfile") 
	git add -A
	git status
	echo
	read -p "Enter your commit message: " git_commit 

	git commit -m "$git_commit"  
	git push
	break
}

while true; 
do
	case $1 in
		push) git_push ;;
		init) git_init ;;
		*)	printf "No valid option (init|push) entered... Shall therefore show the current status\n\n"
			chk_init
			git -C $(< "$HOME/.config/mkdotfile") status
			exit 1 
		;;
	esac
done

IFS=$old_ifs
